# Generated by Django 4.2.3 on 2023-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('ddetails', models.CharField(max_length=400)),
                ('dpic', models.ImageField(upload_to='designs/')),
            ],
        ),
    ]
