# Generated by Django 4.2.3 on 2023-09-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_designs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=50)),
                ('sduration', models.CharField(max_length=100)),
                ('sinvest', models.CharField(max_length=100)),
                ('ssponsor', models.CharField(max_length=100)),
            ],
        ),
    ]
