# Generated by Django 4.2.3 on 2023-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sponsored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rdetails', models.CharField(max_length=400)),
                ('rpic', models.ImageField(upload_to='research/')),
            ],
        ),
    ]
