# Generated by Django 4.2.3 on 2023-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='link',
            field=models.URLField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='designs',
            name='ddetails',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='stitle',
            field=models.CharField(max_length=200),
        ),
    ]
