# Generated by Django 4.2.3 on 2023-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_journal_link_alter_designs_ddetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
