# Generated by Django 4.2.3 on 2023-09-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_journal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='link',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='jour',
            field=models.CharField(max_length=500),
        ),
    ]
