# Generated by Django 4.2.3 on 2023-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='student_type',
            field=models.CharField(choices=[('PhD', 'Ph.D Student'), ('MTech', 'M.Tech Student')], default='', max_length=10),
        ),
    ]
