# Generated by Django 4.2.3 on 2023-12-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_person_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='student_type',
            field=models.CharField(choices=[('PhD', 'Ph.D Student'), ('MTech', 'M.Tech Student'), ('RA', 'Research Associate'), ('Intern', 'Intern'), ('Alumni', 'Alumni')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_title', models.TextField(blank=True)),
                ('fiele_of_interest', models.TextField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('paper_published', models.TextField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.TextField(blank=True)),
                ('skill_expertise', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('membership', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicInfo', models.TextField()),
                ('aboutMe', models.TextField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
