# Generated by Django 4.2.3 on 2023-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_person_student_type_researchinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pduration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_type',
            field=models.CharField(choices=[('PhD', 'Ph.D Student'), ('MTech', 'M.Tech Student'), ('RA', 'Research Associate'), ('Intern', 'Intern'), ('Alumni(P)', 'Alumni(Ph.d)'), ('Alumni(M)', 'Alumni(Masters)')], default='', max_length=20),
        ),
    ]
