# Generated by Django 4.2.3 on 2023-12-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_person_pduration_person_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='pposition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='restitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
