# Generated by Django 4.2.3 on 2023-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_person_dept_person_pposition_person_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pposition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='program',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='restitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
