# Generated by Django 4.2.3 on 2023-12-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_person_dept_alter_person_pposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='glink',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
