# Generated by Django 4.2.3 on 2023-12-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_person_glink'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blink',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
