# Generated by Django 4.2.3 on 2023-12-26 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_person_blink'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='me',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
