# Generated by Django 4.2.3 on 2023-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_about_aboutme_alter_about_academicinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pduration',
        ),
        migrations.AddField(
            model_name='person',
            name='endMonth',
            field=models.CharField(blank=True, choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'Aug'), ('09', 'Sept'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='endYear',
            field=models.CharField(blank=True, choices=[(1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='nowAt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='projectTitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='researcharea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='researchtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='startMonth',
            field=models.CharField(blank=True, choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'Aug'), ('09', 'Sept'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='startYear',
            field=models.CharField(blank=True, choices=[(1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], max_length=5),
        ),
        migrations.AddField(
            model_name='person',
            name='thesisTitle',
            field=models.TextField(blank=True),
        ),
    ]
