# Generated by Django 4.2.3 on 2023-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_person_pduration_person_endmonth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='researcharea',
        ),
        migrations.RemoveField(
            model_name='person',
            name='researchtitle',
        ),
        migrations.AddField(
            model_name='person',
            name='pduration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='researchArea',
            field=models.TextField(blank=True),
        ),
    ]
