# Generated by Django 4.2.3 on 2023-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_person_researcharea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='researchArea',
            new_name='researcharea',
        ),
        migrations.AddField(
            model_name='person',
            name='researchtitle',
            field=models.TextField(blank=True),
        ),
    ]
