# Generated by Django 4.2.3 on 2023-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_person_endyear_alter_person_startyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='endMonth',
            field=models.CharField(blank=True, choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'Aug'), ('09', 'Sept'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec'), ('13', 'Now')], max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='startMonth',
            field=models.CharField(blank=True, choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'Aug'), ('09', 'Sept'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec'), ('13', 'Now')], max_length=5),
        ),
    ]
