# Generated by Django 4.2.3 on 2023-12-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_person_endmonth_alter_person_startmonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pposition',
        ),
    ]
