# Generated by Django 4.2.3 on 2023-12-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_person_pposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ppic',
            field=models.ImageField(blank=True, upload_to='person/'),
        ),
    ]
