# Generated by Django 4.2.3 on 2023-12-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_person_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pmail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
