# Generated by Django 4.2.3 on 2023-12-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_journal_jour_journal_auth_journal_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='conf',
        ),
        migrations.AddField(
            model_name='conference',
            name='auth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='conference',
            name='journal',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='conference',
            name='pinfo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='conference',
            name='ptitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conference',
            name='pyear',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
