# Generated by Django 4.2.3 on 2023-12-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_patent_pat_patent_auth_patent_gon_patent_pno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='rpic',
            field=models.ImageField(blank=True, upload_to='research/'),
        ),
    ]
