# Generated by Django 4.2.3 on 2023-12-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_research_rdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=500)),
                ('npic', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
