# Generated by Django 4.2.3 on 2023-12-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='npic',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
    ]
