# Generated by Django 4.2.3 on 2023-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ndetails',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
