# Generated by Django 4.2.3 on 2023-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='job_type',
            field=models.CharField(choices=[('current', 'Current Openings'), ('research', 'Research Students'), ('interns', 'Internship/Projects')], default='', max_length=20),
        ),
    ]
