# Generated by Django 4.2.3 on 2023-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_join_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='join',
            name='jdur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='join',
            name='qualifications',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='join',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='join',
            name='salary',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
