# Generated by Django 4.2.3 on 2023-12-30 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_join_desc_alter_join_jdur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='link',
            field=models.URLField(blank=True, default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
