# Generated by Django 4.2.3 on 2024-01-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_join_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='topic',
            field=models.CharField(choices=[('shape', 'Shape Understanding'), ('motion', 'Motion Understanding'), ('interaction', 'Interaction & Behaviour Understanding'), ('designdev', 'Product Design & Development')], default='', max_length=20),
        ),
    ]
