# Generated by Django 4.2.3 on 2024-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_research_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='rdetails',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
